### ISSUE TITLE
Float32FlatTriangle get_size , set_size function not available

### ISSUE THREAD

**Issue by edwinsyarief** [nanjizal/trilateral2#2]
Hi,

Thank you for this amazing framework. I have a problem when using trilateral2 pen. At line 35 & 36 error that verts.get_size and verts.set_size not available.

Thank you

**Comment by edwinsyarief** [comment]
Sorry, nevermind, my vscode problem

**Comment by nanjizal** [comment]
@edwinsyarief this repository is no longer relevant I have moved to trilateral3 ( requires haxe 4.2 module level function feature ).
